### ISSUE TITLE
Pokemon-classes or load them from .json file

### ISSUE THREAD

**Issue by MarcusTalbotNL** [Splinxyy/CommunityTextBasedPokemon#11]
Currently we have a Pokemon superclass, and the actual different species of pokemon are subclasses, but this does seem very slow to maintain. Instead we could store the data we need per pokemon in a .json file, and load them from there. What do you think? @Splinxyy

**Comment by MarcusTalbotNL** [comment]
Same could go for all the items and such, by the way.

**Comment by Splinxyy** [comment]
JSON formatting is also a pain though. And it does mean doing the same thing, just with JSON formatting as well as loading and saving from that....

**Comment by MarcusTalbotNL** [comment]
Yeah, fair enough. Don't really feel like writing a JSON parser right now anyway, and using a library such as gson might be slightly overkill as well.
