### ISSUE TITLE
Making a list of features to come, and assigning ourselves to them one at a time

### ISSUE THREAD

**Issue by MarcusTalbotNL** [Splinxyy/CommunityTextBasedPokemon#14]
Hey @Splinxyy ,

The outline of the program is coming along nicely, but I do believe we might start to work on the same features at some point, which would be counterproductive, and really just very confusing. So, how about we write a list of features, that need to be implemented, and start by assigning ourselves to them one at a time. That way we can keep working, others who may want to work on the program know where to start, and we won't get duplicate features.

Wonder what your thoughts on this are.

**Comment by Splinxyy** [comment]
I think that's perfect! Great Idea. I'm available today, also.

**Comment by MarcusTalbotNL** [comment]
Ah great! I was thinking we could just add a textfile to the repository with proposed feautures, and once we agree on a feature, we could update the README to show a list of upcoming features and the assignees. What do you think about that?

**Comment by Splinxyy** [comment]
Readme would be good.
